name: Deploy Github Pages

on:
  push:
    tags:
      - '*'

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x icons/serialize.sh

      - name: Serialize icon names
        run: sh icons/serialize.sh

      - name: Setup for Deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PORTFOLIO_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
          MY_EMAIL: mathubenard@gmail.com
          MY_NAME: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository }}

        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git remote set-url origin https://$MY_NAME:$PORTFOLIO_TOKEN@github.com/$MY_NAME/$MY_NAME.git
          # git remote set-url origin https://$MY_NAME:$GITHUB_TOKEN@github.com/$REPO_NAME.git
          # git remote add upstream https://$MY_NAME:$PORTFOLIO_TOKEN@github.com/$MY_NAME/$MY_NAME.git

      - uses: actions/setup-node@v3
        with:
          node-version: 18.19

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Deploy
        run: |
          pnpm run build
          pnpm run deploy
