name: Deploy Github Pages

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup for Deployments
        # env:
        #   MY_EMAIL: mathubenard@gmail.com
        #   MY_NAME: ben-mathu
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git remote set-url origin https://$MY_NAME:${{ secrets.GITHUB_SECRET }}@github.com/ben-mathu/ben-mathu.git
          git config --global credential.helper 'cache --timeout 3600'

      - uses: actions/setup-node@v3
        with:
          node-version: 18.13

      - name: Install Dependencies
        run: npm i

      - name: Link Angular
        run: npm link @angular/cli

      - name: Deploy to Github Pages
        run: ng deploy --base-href=https://ben-mathu.github.io/ben-mathu --no-silent
