name: Serialization

on:
  push:
    branches:
      - develop

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Serialize icon names
        run: sh icons/serialize.sh
