name: Serialization

on:
  push:
    branches:
      - develop

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x icons/serialize.sh

      - name: Serialize icon names
        run: ./icons/serialize.sh

      - name: Print File Gen
        run: cat icons/data/svg_files.json
